/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum07.view;

import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author basti
 */
public class Window extends javax.swing.JFrame {

  /**
   * @return the ExitButton
   */
  public javax.swing.JMenuItem getExitButton()
  {
    return ExitButton;
  }

  /**
   * @return the OpenButton
   */
  public javax.swing.JMenuItem getOpenButton()
  {
    return OpenButton;
  }

  /**
   * @return the SaveButton
   */
  public javax.swing.JMenuItem getSaveButton()
  {
    return SaveButton;
  }

  /**
   * @return the graphicViewer1
   */
  public praktikum07.view.GraphicViewer getGraphicViewer1()
  {
    return graphicViewer1;
  }

    /**
     * Creates new form Fenster
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicViewer1 = new praktikum07.view.GraphicViewer();
        jMenuBar = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        OpenButton = new javax.swing.JMenuItem();
        SaveButton = new javax.swing.JMenuItem();
        PrintButton = new javax.swing.JMenuItem();
        ExitButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 600));
        getContentPane().add(graphicViewer1, java.awt.BorderLayout.CENTER);

        jFileMenu.setText("File");

        OpenButton.setText("Open");
        jFileMenu.add(OpenButton);

        SaveButton.setText("Save");
        jFileMenu.add(SaveButton);

        PrintButton.setText("Print");
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });
        jFileMenu.add(PrintButton);

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jFileMenu.add(ExitButton);

        jMenuBar.add(jFileMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ExitButtonActionPerformed
  {//GEN-HEADEREND:event_ExitButtonActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_ExitButtonActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitButton;
    private javax.swing.JMenuItem OpenButton;
    private javax.swing.JMenuItem PrintButton;
    private javax.swing.JMenuItem SaveButton;
    private praktikum07.view.GraphicViewer graphicViewer1;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getPrintButton() {
        return PrintButton;
    }

}
