/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum05.View;

import java.awt.Label;
import javax.swing.JButton;

/**
 *
 * @author Leon
 */
public class View extends javax.swing.JFrame
{

  /**
   * Creates new form View
   */
  public View()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    GamblingPanel = new javax.swing.JPanel();
    lblZahl0 = new java.awt.Label();
    lblZahl1 = new java.awt.Label();
    lblZahl2 = new java.awt.Label();
    ControlPanel = new javax.swing.JPanel();
    btnStop = new javax.swing.JButton();
    btnStart = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    GamblingPanel.setBackground(new java.awt.Color(41, 130, 0));
    GamblingPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    GamblingPanel.setPreferredSize(new java.awt.Dimension(250, 135));
    GamblingPanel.setLayout(new java.awt.GridLayout(1, 3));

    lblZahl0.setAlignment(java.awt.Label.CENTER);
    lblZahl0.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
    lblZahl0.setForeground(new java.awt.Color(210, 2, 2));
    lblZahl0.setText("7");
    GamblingPanel.add(lblZahl0);

    lblZahl1.setAlignment(java.awt.Label.CENTER);
    lblZahl1.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
    lblZahl1.setForeground(new java.awt.Color(210, 2, 2));
    lblZahl1.setText("7");
    GamblingPanel.add(lblZahl1);

    lblZahl2.setAlignment(java.awt.Label.CENTER);
    lblZahl2.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
    lblZahl2.setForeground(new java.awt.Color(210, 2, 2));
    lblZahl2.setText("7");
    GamblingPanel.add(lblZahl2);

    getContentPane().add(GamblingPanel, java.awt.BorderLayout.PAGE_START);

    ControlPanel.setBackground(new java.awt.Color(41, 130, 0));
    ControlPanel.setMaximumSize(new java.awt.Dimension(32000, 40));
    ControlPanel.setPreferredSize(new java.awt.Dimension(159, 33));

    btnStop.setText("Stop");
    btnStop.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnStopActionPerformed(evt);
      }
    });
    ControlPanel.add(btnStop);

    btnStart.setText("Start");
    ControlPanel.add(btnStart);

    getContentPane().add(ControlPanel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnStopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStopActionPerformed
  {//GEN-HEADEREND:event_btnStopActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnStopActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new View().setVisible(true);
      }
    });
  }

  public JButton getBtnStart()
  {
    return btnStart;
  }

  public JButton getBtnStop()
  {
    return btnStop;
  }

  public Label getLblZahl0()
  {
    return lblZahl0;
  }

  public Label getLblZahl1()
  {
    return lblZahl1;
  }

  public Label getLblZahl2()
  {
    return lblZahl2;
  }

  
  
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ControlPanel;
  private javax.swing.JPanel GamblingPanel;
  private javax.swing.JButton btnStart;
  private javax.swing.JButton btnStop;
  private java.awt.Label lblZahl0;
  private java.awt.Label lblZahl1;
  private java.awt.Label lblZahl2;
  // End of variables declaration//GEN-END:variables
}
