/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum08;

/**
 *
 * @author Leon
 */
public class ChatView extends javax.swing.JFrame
{

  /**
   * Creates new form ChatView
   */
  public ChatView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    ChatPanel = new javax.swing.JPanel();
    ScrollPane = new javax.swing.JScrollPane();
    ChatTextArea = new javax.swing.JTextArea();
    ControlsPanel = new javax.swing.JPanel();
    ServerCheckbox = new javax.swing.JCheckBox();
    SendButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    ChatTextArea.setColumns(20);
    ChatTextArea.setRows(10);
    ChatTextArea.setMinimumSize(new java.awt.Dimension(13, 1000));
    ScrollPane.setViewportView(ChatTextArea);

    ChatPanel.add(ScrollPane);

    ControlsPanel.setLayout(new java.awt.GridLayout(1, 2));

    ServerCheckbox.setText("Act as Server");
    ServerCheckbox.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ServerCheckboxActionPerformed(evt);
      }
    });
    ControlsPanel.add(ServerCheckbox);

    SendButton.setText("Send");
    ControlsPanel.add(SendButton);

    ChatPanel.add(ControlsPanel);

    getContentPane().add(ChatPanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void ServerCheckboxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ServerCheckboxActionPerformed
  {//GEN-HEADEREND:event_ServerCheckboxActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ServerCheckboxActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new ChatView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ChatPanel;
  private javax.swing.JTextArea ChatTextArea;
  private javax.swing.JPanel ControlsPanel;
  private javax.swing.JScrollPane ScrollPane;
  private javax.swing.JButton SendButton;
  private javax.swing.JCheckBox ServerCheckbox;
  // End of variables declaration//GEN-END:variables
}
